name: climateEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - netcdf4
  - python[version='>=3.8']
  - ipython
  - xarray
  - numpy=1.20.2
  - networkit
  - pot
  - xlrd
  - networkx
  - pip
  - scipy
  - cartopy=0.18.0
  - matplotlib=3.3.4
  - ipywidgets
  - scikit-learn
