name: seminarEnv
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - jupyter
  - python[version='>=3.8']
  - ipython
  - ipywidgets
  - pip
  - xarray
  - netcdf4
  - numpy
  - scipy
  - matplotlib=3.3.4
  - cartopy
  - networkit
  - networkx
  - scikit-learn
  - pytorch
  - torchvision
